In [1]:
# Copyright 2023, Acadential, All rights reserved.

# 2-5. PyTorch 기초 - Tensor

## Tensor란?

Tensor란 데이터를 표현하는 단위로, 다차원 배열의 일반화된 모습입니다. \
PyTorch에서 Tensor을 가지고 연산을 수행하면, 해당 연산은 Computational Graph 상에 표현되고, 나중에 Backward propagation을 통해 Gradient를 계산할 수 있습니다.

## Initializing a tensor

Tensor을 정의하는 방법은 다음과 같습니다.

1. 지정된 값으로 초기화
2. 랜던한 값으로 초기화
3. Numpy array로부터 초기화

In [3]:
# Import related library
import numpy as np 
import torch 

## 초기화 방법 1: 지정된 값으로 Tensor 초기화

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [ ]:
print(torch.tensor.__doc__)

In [5]:

x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
x_data.dtype  # data type is automatically inferred

torch.int64

## 초기화 방법 2: 랜덤한 값으로 Tensor 초기화
* 이를 통해 Tensor를 원하는 형태의 shape으로 초기화가 가능하다.
* 어떤 shape의 tensor를 만들 때 일일이 값을 넣기 귀찮을 때 활용한다.

In [6]:
# 행이2개고 열이3개인 shape
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape) # 1로만 구성된 tensor
zeros_tensor = torch.zeros(shape) # 0로만 구성된 tensor

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0468, 0.9553, 0.1223],
        [0.4175, 0.6934, 0.9552]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 초기화 방법 3: Numpy 배열로부터 Tensor 초기화

In [7]:
data = [[1, 2],[3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
x_np.dtype

torch.int64

# Tensor 데이터의 형식 지정

Tensor의 데이터 형식은 어떤 것들이 있을까요?

1. 정수 int (integer) \
    1-1. ```torch.int8```, ```torch.int16```, ```torch.int32```, ```torch.int64``` (=```torch.long```) \
    1-2. ```torch.uint8```: unsigned integer로 양의 정수 0 ~ 255 숫자만 포함, 주로 이미지 데이터를 다룰 때 사용.
2. float \
    2-1. ```torch.float16```, ```torch.float32```, ```torch.float64``` 
3. boolean: ```torch.bool```
4. etc.



### torch.float32 형식으로 초기화

In [18]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data, dtype=torch.float32)

In [19]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [20]:
x_data.dtype

torch.float32

### torch.uint8 형식으로 초기화

In [25]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data, dtype=torch.uint8)

In [26]:
x_data

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

### 다른 dtype으로 변환

In [27]:
x_data = x_data.to(torch.float16)

In [28]:
x_data.dtype

torch.float16

# 다른 Device로 Tensor 옮기기

1. GPU가 사용가능한지 확인하기
2. 다른 Device로 Tensor 옮기기
3. 어떤 Device상에 Tensor가 있는지 확인하기

### GPU가 사용가능한지 확인하기

In [44]:
torch.cuda.is_available()

False

### GPU로 Tensor 옮기기

In [45]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    x_data = x_data.to("cuda")

### CPU로 Tensor 옮기기

In [46]:
x_data = x_data.cpu()
x_data = x_data.to("cpu")

### 어떤 Device상에 Tensor가 있는지 확인하기

In [47]:
x_data.device

device(type='cpu')

# Tensor을 활용한 연산
## 대부분의 연산은 numpy와 유사
1. Indexing and slicing
2. Concatenation
3. Arithmetric
4. Inplace-operation

### Indexing 
* index을 통해서 tensor의 특정 index의 값을 가져오거나 변형할 수 있다.

In [48]:
tensor = torch.ones(4, 4)

In [49]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concatenation
* 복수의 텐서를 이어붙이는 연산

In [52]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithmetric
* 행렬의 곱

In [53]:
# 행렬의 곱 : @, matmul
y1 = tensor @ tensor.T  # .T는 transpose
y2 = tensor.matmul(tensor.T)

# Element-wise 곱셈 : *, mul
z1 = tensor * tensor
z2 = tensor.mul(tensor)

In [56]:
print(y1)
print()
print(y2)
print()
print(z1)
print()
print(z2)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Inplace operation
* 기존의 정의된 텐서에 해당연산을 수행한 후 inplace 해주는 명령어이다.

In [57]:
print(f"{tensor} \n")
tensor.add_(5) # tensor에 5를 더해주고 override 해주는 것을 의미함.
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
